# Generated by Django 5.2.3 on 2025-06-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Message2Manager',
        ),
    ]
