# Generated by Django 5.2.3 on 2025-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message_delete_message2manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
