# Generated by Django 5.2.3 on 2025-06-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
